import { ChangeEvent, createContext } from "react";

const PemesananPaketWisataContext = createContext({
    onTitelChange: (e: ChangeEvent<HTMLSelectElement>) => {},
    onNamaChange: (e: ChangeEvent<HTMLInputElement>) => {},
    onNomorKtpChange: (e: ChangeEvent<HTMLInputElement>) => {},
    onNomorTeleponChange: (e: ChangeEvent<HTMLInputElement>) => {},
    onTitelDewasasChange: (e: ChangeEvent<HTMLSelectElement>, i: number) => {},
    onNamaDewasasChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onTanggalDewasasChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onTitelAnaksChange: (e: ChangeEvent<HTMLSelectElement>, i: number) => {},
    onNamaAnaksChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onTanggalAnaksChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onTitelBayisChange: (e: ChangeEvent<HTMLSelectElement>, i: number) => {},
    onNamaBayisChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onTanggalBayisChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onNamaDepanTengahDewasasChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onNamaDepanTengahAnaksChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onNamaDepanTengahBayisChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onNamaBelakangDewasasChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onNamaBelakangAnaksChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onNamaBelakangBayisChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onNomorPasporDewasasChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onNomorPasporAnaksChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onNomorPasporBayisChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onTanggalHabisBerlakuDewasasChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onTanggalHabisBerlakuAnaksChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    onTanggalHabisBerlakuBayisChange: (e: ChangeEvent<HTMLInputElement>, i: number) => {},
    setCurrentPosition: (n: 1|2|3) => {},
    setTipePembayaran: (v: string) => {},
    titelDewasas: [""],
    namaDewasas: [""],
    tanggalDewasas: [""],
    titelAnaks: [""],
    namaAnaks: [""],
    tanggalAnaks: [""],
    titelBayis: [""],
    namaBayis: [""],
    tanggalBayis: [""],
    currentPosition: 1,
    tipePaketWisata: "dalam_negeri",
    tipePembayaran: "",
    namaDepanTengahDewasas: [""],
    namaDepanTengahAnaks: [""],
    namaDepanTengahBayis: [""],
    namaBelakangDewasas: [""],
    namaBelakangAnaks: [""],
    namaBelakangBayis: [""],
    nomorPasporDewasas: [""],
    nomorPasporAnaks: [""],
    nomorPasporBayis: [""],
    tanggalHabisBerlakuDewasas: [""],
    tanggalHabisBerlakuAnaks: [""],
    tanggalHabisBerlakuBayis: [""],
    titel: "",
    nama: "",
    nomorKtp: "",
    noTelepon: ""
});

export default PemesananPaketWisataContext;